{-# LANGUAGE FlexibleInstances          #-}
{-# LANGUAGE UndecidableInstances       #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE TypeFamilies               #-}
{-

Declares the yesod dispatch instance for the admin subsite. This is
autogenerated from the Y.A.Resource via Template haskell. So expect an
ugly Haddock.

-}

module Yesod.Admin.Dispatch where

import Yesod.Admin.Types
import Yesod.Admin.Resource
import Yesod.Admin.Routes
import Yesod.Admin.Handlers.Internal

getCrud :: Selection master v -> Crud master v
getCrud = const Crud
mkAdminDispatch "master" "v"
