{-|

This modules defines some type convenient type aliases

-}

module Yesod.Admin.Types
       ( Admin
       , getAdmin
       , Crud(..)
       , Selection(..)
       , SiteKey
       , SiteKVPair
       , DBAction(..)
       , CrudHandler
       , CrudWidget
       , SelectionHandler
       , SelectionWidget
       ) where

import Yesod
import Database.Persist.Query.Internal

-- | The admin subsite. This is the subsite which has to be hooked
-- into the main site. All entity specific Crud and Selection sites
-- will be subsites of this type. The exact list of entities will be
-- known only when this is used. So defining the `RenderRoute` and
-- `YesodDispatch` instance of this type is not possible in this
-- library: they are generated by TH code at the point of usage.
data Admin master = Admin

getAdmin :: master -> Admin master
getAdmin _ = Admin

-- | The crud subsite
data Crud master v = Crud

-- | The selection subsite
data Selection master v = Selection

{-|

We assume that the master site is an instance of YesodPersist. This is
an alias for the database key to access element of type v.

-}

type SiteKey master v = Key (YesodPersistBackend master) v

{-|

This type captures the admin key value pairs. Key value pairs are
returned by many of the database functions. It is good to have this
type defined.

-}

type SiteKVPair master v = (SiteKey master v, v)

-- | This types captures actions that can be applied from selection
-- page.

data DBAction b m v = DBDelete            -- ^ A delete action
                    | DBUpdate (Update v) -- ^ An update action
                    | DBCustom { runCustomAction :: Key b v -> b m () }
                                            -- ^ A custom action

-- | A type alias for widgets of the admin subsite.
type CrudWidget  master v  = GWidget  (Crud master v) master

-- | A type alias for handlers of the admin subsite.
type CrudHandler master v  = GHandler (Crud master v) master


-- | A type alias for widgets of the selection subsite.
type SelectionWidget  master v  = GWidget  (Selection master v) master

-- | A type alias for handlers of the selection subsite.
type SelectionHandler master v  = GHandler (Selection master v) master
